spring.application.name=batch-noti
spring.datasource.url=jdbc:postgresql://localhost:5432/batchdb?reWriteBatchedInserts=true
batch.chunk.size=5000
spring.batch.job.enabled=false
#spring.batch.jdbc.initialize-schema=always
